{{- if .Values.secretEnvs}}
apiVersion: v1
kind: Secret
metadata:
  name: env-secret
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}
    component: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  AIRFLOW_PWD: {{ .Values.secretEnvs.AIRFLOW_PWD | b64enc | quote }}
  FERNET_KEY: {{ .Values.secretEnvs.FERNET_KEY | b64enc | quote }}
{{- end }}