apiVersion: v1
kind: Service
metadata:
  name: {{ include "bdw-cp-connector-chart.fullname" . }}
  labels:
    {{- include "bdw-cp-connector-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "bdw-cp-connector-chart.selectorLabels" . | nindent 4 }}
