---
{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: keyfile-config
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}
    component: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- with .Values.persistence.configFile }}
    {{- toYaml . | trimSuffix "\n" | nindent 2 }}
  {{- end }}
{{- end }}

---
{{- if .Values.configEnvs}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: sink-env-configmap
  labels:
    app: {{ .Chart.Name }}
    chart: {{ .Chart.Name }}
    component: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- with .Values.configEnvs }}
    {{- toYaml . | trimSuffix "\n" | nindent 2 }}
  {{- end }}
{{- end }}