{{ config(materialized='incremental', alias='ac_ar', unique_key='ac_ar_id')}} 
 
with source_data as (
    SELECT  
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as ac_ar_id,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as ac_tp_id,
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as bal_au_id,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as rstrc_dscl_tp_id,
            {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("timestamp")) }} 	as last_stmt_dt,
            {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("timestamp")) }} 	as last_txn_dt,
            {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("timestamp")) }} 	as crn_fix_prd_end_dt,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as int_acg_f,
            {{ col_cast("'1'", "varchar", "20") }} 	as ac_nbr,
            {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("timestamp")) }} 	as int_clcn_eff_dt,
            {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("timestamp")) }} 	as nxt_cmpd_int_dt,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as exec_polcy_ccnt_f,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as non_mkt_exec_ccnt_f,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as exrnc_wrn_f,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as ar_inapt_f,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as best_exec_polcy_f,
            {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("timestamp")) }} 	as best_exec_dt,
            {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("timestamp")) }} 	as aml_mond_dt,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as xtrt_f,
            {{ col_cast("'1'", "varchar", "20") }} 	as itnl_bnkg_ac_nbr,
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as scr_ar_id,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as ivsm_own_tp_id,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as ivsm_objv_tp_id,
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as cptl_prj_pybk_no_of_yr,
            {{ col_cast("'1'", "varchar", "1") }}  as prvt_x_pblc_ivsm_ind,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 6, 2)) }} 	as inr_rate_of_ret,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as ivsm_hrzn_id,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as fnd_shr_issu_tp_id,
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as prn_fnd_ivsm_id,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as mtl_fnd_f,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as mgn_fnd_f,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as ivsr_rstn_f,
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as rsk_cty_id,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as day_trdg_f,
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as sutbl_verf_by_id,
            {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("timestamp")) }} 	as sutbl_verf_dt,
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as ac_aprv_by_id,
            {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("timestamp")) }} 	as ac_aprv_dt,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as ac_lng_id,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as cmm_adr_tp_id,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as trdg_mand_ahr_tp_id,
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as bnch_pd_id,
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as dflt_ivsm_pd_id,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as src_of_incm_tp_id,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as trdg_st_tp_id,
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as ins_polcy_doc_id,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as ins_tp_id,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as ins_hzd_tp_id,
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as ins_pd_id,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as ins_ar_payer_tp_id,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as ins_pd_cmpt_nbr
), columns_prep as (
    select acc.account_id as ac_ar_id,
            acc.frequency as ac_tp_id, 
            bal_au_id, rstrc_dscl_tp_id, last_stmt_dt, last_txn_dt, crn_fix_prd_end_dt,
            int_acg_f, 
            ac_nbr,
            int_clcn_eff_dt, nxt_cmpd_int_dt, exec_polcy_ccnt_f, non_mkt_exec_ccnt_f,
            exrnc_wrn_f, ar_inapt_f, best_exec_polcy_f, best_exec_dt, aml_mond_dt, xtrt_f, itnl_bnkg_ac_nbr,
            scr_ar_id, ivsm_own_tp_id, ivsm_objv_tp_id, cptl_prj_pybk_no_of_yr, prvt_x_pblc_ivsm_ind,inr_rate_of_ret,
            ivsm_hrzn_id, fnd_shr_issu_tp_id, prn_fnd_ivsm_id, mtl_fnd_f, mgn_fnd_f, ivsr_rstn_f, rsk_cty_id,
            day_trdg_f, sutbl_verf_by_id, sutbl_verf_dt, ac_aprv_by_id, 
            acc.parseddate as ac_aprv_dt,
            ac_lng_id, 
            acc.district_id as cmm_adr_tp_id, 
            trdg_mand_ahr_tp_id,
            bnch_pd_id, dflt_ivsm_pd_id, src_of_incm_tp_id, trdg_st_tp_id, ins_polcy_doc_id, ins_tp_id, ins_hzd_tp_id,
            ins_pd_id, ins_ar_payer_tp_id,ins_pd_cmpt_nbr,
            {{ col_cast(var("batch_nbr", "a_batch_nbr"), "varchar", "25") }} as batch_nbr,
            current_timestamp as load_time
    from {{ source('rawdata', 'completed_account') }} as acc
    left join source_data as srd
    on acc.account_id = srd.ac_nbr

)

 select * from columns_prep