{{ config(materialized='incremental', alias='sa_ar', unique_key='ar_id')}} 
 
with source_data as (
    SELECT
        {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as ar_id,
        {{ col_cast("'1'", "varchar", "10") }} 	as src_sys_cd,
        {{ col_cast("'1'", "varchar", "256") }} 	as src_sys_unq_key_txt,
        {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("timestamp")) }} 	as effv_ts,
        {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("timestamp")) }} 	as end_ts,
        {{ col_cast("'1'", "varchar", "10") }} 	as tnnt_cd_id,
        {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as btch_id,
        {{ col_cast("'1'", "varchar", "32") }} 	as ar_ty_id,
        {{ col_cast("'1'", "varchar", "32") }} 	as ar_freq_ty_id,
        {{ col_cast("'1'", "varchar", "32") }} 	as ar_prps_ty_id,
        {{ col_cast("'1'", "varchar", "32") }} 	as ar_rsn_ty_id,
        {{ col_cast("'1'", "varchar", "32") }} 	as ar_prmy_pmt_methd_id,
        {{ col_cast("'1'", "varchar", "32") }} 	as ar_fnc_sts_ty_id,
        {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("timestamp")) }} 	as ar_fnc_sts_dt,
        {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("timestamp")) }} 	as ar_lc_sts_dt,
        {{ col_cast("'1'", "varchar", "32") }} 	as ar_lc_sts_ty_id,
        {{ col_cast("'1'", "varchar", "32") }} 	as ar_phase_id,
        {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("timestamp")) }} 	as ar_phase_dt,
        {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("timestamp")) }} 	as prmy_resp_cntr_dt,
        {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as prmy_resp_cntr_id,
        {{ col_cast("'1'", "varchar", "32") }} 	as ar_trm_ty_id,
        {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as orig_chnl_id,
        {{ col_cast("'1'", "varchar", "32") }} 	as dnmntn_cur_id,
        {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as nbr_of_ar_cvrd,
        {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as init_ip_id,
        {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as rprst_ou_id,
        {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("timestamp")) }} 	as estmtd_end_dt,
        {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("timestamp")) }} 	as effv_dt,
        {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("timestamp")) }} 	as end_dt,
        {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("timestamp")) }} 	as lst_cust_actvty_dt,
        {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("timestamp")) }} 	as lst_prcdr_dt,
        {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("timestamp")) }} 	as lst_trms_mod_dt,
        {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("timestamp")) }} 	as nxt_rvw_dt,
        {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("timestamp")) }} 	as lst_rvw_dt,
        {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as rnwl_flg,
        {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("timestamp")) }} 	as nxt_rnwl_dt,
        {{ col_cast("'1'", "varchar", "32") }} 	as ar_nm,
        {{ col_cast("'1'", "varchar", "256") }} 	as {{ add_quote("desc") }},
        {{ col_cast("'1'", "varchar", "32") }} 	as ri_ar_ty_id,
        {{ col_cast("'1'", "varchar", "25") }} 	as batch_nbr,
        {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("timestamp")) }} as loaded_time
)
 SELECT * FROM source_data WHERE 1=2 