{{ config(materialized='incremental', alias='sa_ev_cmm', unique_key='EV_CMM_ID')}} 
 
with source_data as (
    SELECT
            {{ col_cast("'1'", "varchar", "32") }} 	as ev_cmm_id,
            {{ col_cast("'1'", "varchar", "10") }} 	as src_sys_cd,
            {{ col_cast("'1'", "varchar", "256") }} 	as src_sys_unq_key_txt,
            {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("timestamp")) }} 	as effv_ts,
            {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("timestamp")) }} 	as end_ts,
            {{ col_cast("'1'", "varchar", "10") }} 	as tnnt_cd_id,
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as btch_id,
            {{ col_cast("'1'", "varchar", "32") }} 	as ev_ty_id,
            {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("timestamp")) }} 	as ev_lc_sts_ty_dt,
            {{ col_cast("'1'", "varchar", "32") }} 	as ev_lc_sts_ty_id,
            {{ col_cast("'1'", "varchar", "32") }} 	as ev_lc_sts_rsn_ty_id,
            {{ col_cast("'1'", "varchar", "32") }} 	as ev_orgntn_ty_id,
            {{ col_cast("'1'", "varchar", "32") }} 	as prblty_of_occur_cgy_id,
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as ev_src_id,
            {{ col_cast("'1'", "varchar", "32") }} 	as ev_cntct_mdm_ty_id,
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as suspcs_flg,
            {{ col_cast("'1'", "varchar", "32") }} 	as prty_rtng_id,
            {{ col_cast("'1'", "varchar", "10") }} 	as authrztn_cd,
            {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("timestamp")) }} 	as authrztn_dt,
            {{ col_cast("'1'", "varchar", "32") }} 	as ev_prps_ty_id,
            {{ col_cast("'1'", "varchar", "32") }} 	as ev_exctn_mode_id,
            {{ col_cast("'1'", "varchar", "32") }} 	as cmm_ty_id,
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as actn_cmplt_flg,
            {{ col_cast("'1'", "varchar", "1") }} 	as thrd_prtcpt_sts,
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as cmm_prcsng_tm,
            {{ col_cast("'1'", "varchar", "32") }} 	as cmm_cntct_sts_id,
            {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("timestamp")) }} 	as cmm_cntct_sts_dt,
            {{ col_cast("'1'", "varchar", "32") }} 	as cmm_drctn_id,
            {{ col_cast("'1'", "varchar", "32") }} 	as cmm_form_id,
            {{ col_cast("'1'", "varchar", "32") }} 	as cmm_rsn_ty_id,
            {{ col_cast("'1'", "varchar", "32") }} 	as cmm_rspn_ty_id,
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as chnl_id,
            {{ col_cast("'1'", "varchar", "32") }} 	as lang_id,
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as prd_id,
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as init_ip_id,
            {{ col_cast("'1'", "varchar", "32") }} 	as init_tm,
            {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("timestamp")) }} 	as init_dt,
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as rcpnt_ip_id,
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as rspn_tm_in_dys,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as cmm_dcost,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as cmm_icost,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as cmm_fee,
            {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("timestamp")) }} 	as cmm_dt,
            {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("timestamp")) }} 	as cmm_effv_dt,
            {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("timestamp")) }} 	as recvd_dt,
            {{ col_cast("'1'", "varchar", "32") }} 	as recvd_tm,
            {{ col_cast("'1'", "varchar", "32") }} 	as rspn_tm,
            {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("timestamp")) }} 	as rspn_dt,
            {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("timestamp")) }} 	as xprtn_dt,
            {{ col_cast("'1'", "varchar", "32") }} 	as cmm_dely_rsn_ty_id,
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as cmm_thrd_id,
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as prep_tm_for_cmm,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 5)) }} 	as cmm_ohold_tm,
            {{ col_cast("'1'", "varchar", "32") }} 	as cmm_sntm_ty_id,
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as ev_cpgn_id,
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as cmpnavy_nbr,
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as mseg_grp_id,
            {{ col_cast("'1'", "varchar", "32") }} 	as cmpnavy_scenr_id,
            {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("timestamp")) }} 	as cpgn_cmm_effv_dt,
            {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("timestamp")) }} 	as cpgn_cmm_end_dt,
            {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("timestamp")) }} 	as cntct_sel_dt,
            {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("timestamp")) }} 	as rmdr_dt,
            {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("timestamp")) }} 	as nxt_step_dt,
            {{ col_cast("'1'", "varchar", "32") }} 	as scl_meda_post_ty_id,
            {{ col_cast("'1'", "varchar", "2000") }} 	as post_txt,
            {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("timestamp")) }} 	as post_dt,
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as nbr_of_cmnt,
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as nbr_of_pstv_rtg,
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as nbr_of_neg_rtg,
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as scl_meda_psna_id,
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as scl_meda_website_id
), crm_event as (
    select  {{ dbt_utils.generate_surrogate_key(["date_received", "complaint_id", "client_id"]) }} as crm_event_id
            , product 
            , client_id
            , date_received, sub_product, issue, sub_issue, consumer_complaint_narrative, tags
            , is_consumer_consent_provided, submitted_via, date_sent_to_company, company_response_to_consumer
            , is_timely_response, was_consumer_disputed, complaint_id

    FROM {{ source('rawdata', 'crm_event') }}
), columns_prep as (
    select 
        crm_event.crm_event_id as ev_cmm_id,
        crm_log.server as src_sys_cd,
        srd.src_sys_unq_key_txt,
        {{ col_cast("crm_log.ser_start", "varchar", "10") }} as EFFV_TS,
        {{ col_cast("crm_log.ser_exit", "varchar", "10") }} as END_TS,
        crm_log.vru_plus_line as tnnt_cd_id,
        srd.btch_id,
        srd.ev_ty_id,
        srd.ev_lc_sts_ty_dt,
        crm_log.outcome as  ev_lc_sts_ty_id,
        srd.ev_lc_sts_rsn_ty_id,
        srd.ev_orgntn_ty_id,
        srd.prblty_of_occur_cgy_id,
        srd.ev_src_id,
        srd.ev_cntct_mdm_ty_id,
        srd.suspcs_flg,
        crm_log.priority as prty_rtng_id,
        crm_event.is_consumer_consent_provided as authrztn_cd,
        srd.authrztn_dt,
        crm_event.issue as ev_prps_ty_id,
        srd.ev_exctn_mode_id,
        crm_log.type as cmm_ty_id,
        srd.actn_cmplt_flg,
        srd.thrd_prtcpt_sts,
        srd.cmm_prcsng_tm,
        crm_event.company_response_to_consumer as cmm_cntct_sts_id,
        srd.cmm_cntct_sts_dt,
        crm_log.phonefinal as cmm_drctn_id,
        srd.cmm_form_id,
        srd.cmm_rsn_ty_id,
        crm_event.is_timely_response as cmm_rspn_ty_id,
        chnl.chnl_id as chnl_id,
        srd.lang_id,
        prd.prd_id as prd_id,
        ip.ip_id as init_ip_id,
        srd.init_tm,
        srd.init_dt,
        srd.rcpnt_ip_id,
        srd.rspn_tm_in_dys,
        srd.cmm_dcost,
        srd.cmm_icost,
        srd.cmm_fee,
        srd.cmm_dt,
        srd.cmm_effv_dt,
        crm_event.date_received as recvd_dt,
        srd.recvd_tm,
        srd.rspn_tm,
        crm_event.date_sent_to_company as rspn_dt,
        srd.xprtn_dt,
        srd.cmm_dely_rsn_ty_id,
        crm_log.call_id as cmm_thrd_id,
        srd.prep_tm_for_cmm,
        {{ col_cast("crm_log.ser_time", "varchar", "10") }} as CMM_OHOLD_TM,
        crm_event.was_consumer_disputed as cmm_sntm_ty_id,
        crm_event.complaint_id as ev_cpgn_id,
        srd.cmpnavy_nbr,
        srd.mseg_grp_id,
        srd.cmpnavy_scenr_id,
        srd.cpgn_cmm_effv_dt,
        srd.cpgn_cmm_end_dt,
        srd.cntct_sel_dt,
        srd.rmdr_dt,
        srd.nxt_step_dt,
        srd.scl_meda_post_ty_id,
        crm_event.consumer_complaint_narrative as post_txt,
        srd.post_dt,
        srd.nbr_of_cmnt,
        srd.nbr_of_pstv_rtg,
        srd.nbr_of_neg_rtg,
        crm_event.tags as scl_meda_psna_id,
        srd.scl_meda_website_id,
        {{ col_cast(var("batch_nbr", "a_batch_nbr"), "varchar", "25") }} as batch_nbr,
        current_timestamp as load_time
    FROM crm_event
    LEFT JOIN source_data AS srd
    on srd.ev_cmm_id = crm_event.crm_event_id
    LEFT JOIN {{ ref('SA_IP') }} ip
    on crm_event.client_id = ip.src_sys_cd
    LEFT JOIN {{ ref('SA_PRD') }} prd
    on crm_event.product = prd.prd_nm
    LEFT JOIN {{ ref('SA_CHNL') }} AS chnl
    on crm_event.submitted_via = chnl.chnl_txt
    LEFT JOIN {{ source('rawdata', 'crm_call_center_log') }} AS crm_log
    on crm_event.complaint_id = crm_log.complaint_id
) 

 SELECT * FROM columns_prep