{{ config(materialized='incremental', alias='sa_ip_prof', unique_key='ip_id')}} 
 
with source_data as (
    select
            {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("date")) }} 	as effv_dt,
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as dnmntn_cur_id,
            {{ col_cast("'1'", "varchar", "32") }}	as ip_id,
            {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("date")) }} 	as end_dt,
            {{ col_cast("'1'", "varchar", "10") }} 	as src_sys_cd,
            {{ col_cast("'1'", "varchar", "256") }} 	as src_sys_unq_key_txt,
            {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("timestamp")) }} 	as effv_ts,
            {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("timestamp")) }} 	as end_ts,
            {{ col_cast("'1'", "varchar", "10") }} 	as tnnt_cd_id,
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as btch_id,
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as orgnl_cur_id,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 12, 7)) }} 	as xchg_rte_to_orgnl_cur,
            {{ col_cast("'1'", "varchar", "32") }} 	as prfrd_cmm_form_id,
            {{ col_cast("'1'", "varchar", "32") }} 	as prmy_src_of_incm_ty_id,
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as nbr_of_dpndt_chld,
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as nbr_of_depnd,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as mthly_hsng_cost,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as hsng_ins_cost_amt,
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as yrs_at_crnt_addr,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as ho_assoc_fee,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as idv_annl_slry,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as idv_othr_annl_incm,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as idv_net_wrth,
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as idv_age,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as idv_othr_nfnc_asset,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as idv_real_prprty_asset,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as idv_fnc_asset,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as idv_liblty,
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as no_of_memb,
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as no_of_emp,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as fxd_asset,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as crnt_asset,
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as shrt_term_crdtr,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as tot_brrw,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as cap_and_rsrvs,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as annl_pre_tax_proft,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as annl_sale_rev,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as csh_flw,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as three_yr_avg_annl_grs_incm,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as val_add_proft,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 0)) }} 	as tot_eqty,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 5, 2)) }} 	as roe,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as eps,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as avg_shr_prc,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as shr_prc_hi,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as shr_prc_low,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 6, 2)) }} 	as pe_rat,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 6, 2)) }} 	as ern_to_fxd_cost_rat,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 6, 2)) }} 	as asset_trnvr_rat,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 6, 2)) }} 	as debt_to_eqty_rat,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 6, 2)) }} 	as cost_to_incm_rat,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 6, 2)) }} 	as non_ii_rat,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 6, 2)) }} 	as staff_cost_rat,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 6, 2)) }} 	as cost_to_asset_rat,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 6, 2)) }} 	as crnt_rat,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 0)) }} 	as rcptl_amt,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 0)) }} 	as dscrt_cap_amt,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 2)) }} 	as net_wrkng_cap,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 15, 0)) }} 	as llp,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 5, 2)) }} 	as cap_gear,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 5, 2)) }} 	as captl_pct,
            {{ dbt.safe_cast("'1'", api.Column.numeric_type('numeric', 5, 2)) }} 	as roi
), columns_prep as(
    select
            srd.effv_dt,
            srd.dnmntn_cur_id,
            ip.ip_id as ip_id,
            srd.end_dt,
            cp.client_id as src_sys_cd,
            srd.src_sys_unq_key_txt,
            srd.effv_ts,
            srd.end_ts,
            srd.tnnt_cd_id,
            srd.btch_id,
            orgnl_cur_id,
            xchg_rte_to_orgnl_cur,
            prfrd_cmm_form_id,
            prmy_src_of_incm_ty_id,
            nbr_of_dpndt_chld,
            nbr_of_depnd,
            mthly_hsng_cost,
            hsng_ins_cost_amt,
            yrs_at_crnt_addr,
            ho_assoc_fee,
            idv_annl_slry,
            idv_othr_annl_incm,
            idv_net_wrth,
            cp.age as idv_age,
            idv_othr_nfnc_asset,
            idv_real_prprty_asset,
            idv_fnc_asset,
            idv_liblty,
            no_of_memb,
            no_of_emp,
            fxd_asset,
            crnt_asset,
            shrt_term_crdtr,
            tot_brrw,
            cap_and_rsrvs,
            annl_pre_tax_proft,
            annl_sale_rev,
            csh_flw,
            three_yr_avg_annl_grs_incm,
            val_add_proft,
            tot_eqty,
            roe,
            eps,
            avg_shr_prc,
            shr_prc_hi,
            shr_prc_low,
            pe_rat,
            ern_to_fxd_cost_rat,
            asset_trnvr_rat,
            debt_to_eqty_rat,
            cost_to_incm_rat,
            non_ii_rat,
            staff_cost_rat,
            cost_to_asset_rat,
            crnt_rat,
            rcptl_amt,
            dscrt_cap_amt,
            net_wrkng_cap,
            llp,
            cap_gear,
            captl_pct,
            roi,
            {{ col_cast(var("batch_nbr", "a_batch_nbr"), "varchar", "25") }} as batch_nbr,
            current_timestamp as load_time
    from {{ source('rawdata', 'completed_client') }} cp
    left join source_data srd
    on cp.client_id = srd.ip_id
    left join {{ ref('SA_IP') }} ip
    on ip.src_sys_cd = cp.client_id

) 

 select * from columns_prep