{{ config(materialized='incremental', alias='sa_ri', unique_key='ri_id')}} 
 
with source_data as (
    SELECT
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as ri_id,
            {{ col_cast("'1'", "varchar", "10") }} 	as src_sys_cd,
            {{ col_cast("'1'", "varchar", "256") }} 	as src_sys_unq_key_txt,
            {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("timestamp")) }} 	as effv_ts,
            {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("timestamp")) }} 	as end_ts,
            {{ col_cast("'1'", "varchar", "10") }} 	as tnnt_cd_id,
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as btch_id,
            {{ col_cast("'1'", "varchar", "32") }} 	as ri_ty_id,
            {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("date")) }} 	as effv_dt,
            {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("date")) }} 	as end_dt,
            {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("date")) }} 	as ri_lc_sts_dt,
            {{ col_cast("'1'", "varchar", "32") }} 	as ri_lc_sts_ty_id,
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as ownr_id,
            {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("date")) }} 	as ownr_dt,
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as hldr_id,
            {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("date")) }} 	as hldr_dt,
            {{ col_cast("'1'", "varchar", "32") }} 	as ri_signf_id,
            {{ col_cast("'1'", "varchar", "32") }} 	as ri_nm,
            {{ col_cast("'1'", "varchar", "256") }} 	as {{ add_quote("desc") }},
            {{ col_cast("'1'", "varchar", "32") }} 	as non_cltzl_ri_ty_id,
            {{ col_cast("'1'", "varchar", "32") }} 	as doc_itm_ty_id,
            {{ col_cast("'1'", "varchar", "32") }} 	as lang_id,
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as web_addr_id,
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as website_id,
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as website_hme_pg_flg,
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as usr_hme_pg_flg,
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as web_pg_fnt_sz_val,
            {{ col_cast("'1'", "varchar", "32") }} 	as cltzl_ri_ty_id,
            {{ col_cast("'1'", "varchar", "32") }} 	as chtl_ty_id,
            {{ col_cast("'1'", "varchar", "32") }} 	as elcdd_ty_id,
            {{ col_cast("'1'", "varchar", "200") }} 	as elcdd_idfn_cd,
            {{ col_cast("'1'", "varchar", "32") }} 	as hnm,
            {{ col_cast("'1'", "varchar", "32") }} 	as trml_ty_id,
            {{ col_cast("'1'", "varchar", "32") }} 	as trml_lo_ty_id,
            {{ dbt.safe_cast("'1'", api.Column.translate_type("integer")) }} 	as on_site_flg,
            {{ col_cast("'1'", "varchar", "32") }} 	as tlphnc_dvc_ty_id,
            {{ col_cast("'1'", "varchar", "32") }} 	as dvc_mnfctr,
            {{ col_cast("'1'", "varchar", "18") }} 	as dvc_version,
            {{ col_cast("'1'", "varchar", "32") }} 	as dvc_modl,
            {{ col_cast("'1'", "varchar", "32") }} 	as oper,
            {{ col_cast("'1'", "varchar", "25") }} 	as batch_nbr,
            {{ dbt.safe_cast("'2022-06-21T21:00:00'", api.Column.translate_type("timestamp")) }} as loaded_time
) 

 SELECT * FROM source_data WHERE 1=2